---
kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: ldericher/kiwi-backup
    auto_tag: true
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
