#!/bin/sh

this_script="$( readlink -f "${0}" )"
this_dir="${this_script%/*}"

# files
duplicity_secrets_file="/root/duplicity_secrets"

# load secrets file
if [ -f "${duplicity_secrets_file}" ]; then
    # shellcheck disable=SC1090
    . "${duplicity_secrets_file}"
fi

# handle more verbose "GPG_PASSPHRASE" env var
if [ -n "${GPG_PASSPHRASE}" ]; then
    PASSPHRASE="${GPG_PASSPHRASE:-${PASSPHRASE}}"
    export PASSPHRASE
    unset GPG_PASSPHRASE
fi

# run start webhook
/usr/local/libexec/kiwi-cron/run_webhook \
    "${WEBHOOK_URL}" "running task ${*}" "${WEBHOOK_INSECURE}"

# hand over
set -ex
eval "$( \
    "${this_dir}/build_command" \
    "${@}" \
)"
exit_status="${?}"

# run finish webhook
if [ "${exit_status}" -eq "0" ]; then
    /usr/local/libexec/kiwi-cron/run_webhook \
        "${WEBHOOK_URL}" "task ${*} successful" "${WEBHOOK_INSECURE}"

else
    /usr/local/libexec/kiwi-cron/run_webhook \
        "${WEBHOOK_FAIL_URL:-${WEBHOOK_URL}}" "task ${*} failed, status ${exit_status}" "${WEBHOOK_INSECURE}"

fi
