#!/bin/sh

message="$(echo "${2}" | sed "s,\s,%20,g" )"
webhook_url="$(echo "${1}" | sed "s,%%MSG%%,${message},g" )"
webhook_insecure="${3:-0}"


if [ -z "${webhook_url}" ]; then
    return 1
fi


curl_args=""
if [ "${webhook_insecure}" = "1" ]; then
    curl_args="--insecure"
fi

curl ${curl_args} "${webhook_url}" 1>/dev/null 2>/dev/null
