#!/bin/sh

this_script="$( readlink -f "${0}" )"
this_dir="${this_script%/*}"

echo "${SCHEDULE_BACKUP}"  "${this_dir}/run_command backup" \
  | /usr/local/libexec/kiwi-cron/randomize_schedule

echo "${SCHEDULE_CLEANUP}" "${this_dir}/run_command cleanup" \
  | /usr/local/libexec/kiwi-cron/randomize_schedule

echo "${SCHEDULE_RMFULL}"  "${this_dir}/run_command rmfull" \
  | /usr/local/libexec/kiwi-cron/randomize_schedule

echo "${SCHEDULE_RMINCR}"  "${this_dir}/run_command rmincr" \
  | /usr/local/libexec/kiwi-cron/randomize_schedule
