#!/bin/sh

this_script="$( readlink -f "${0}" )"
this_dir="${this_script%/*}"

echo "${SCHEDULE_BACKUP}"  "$( "${this_dir}/build_command" backup )" \
  | /usr/local/libexec/kiwi-cron/randomize_schedule

echo "${SCHEDULE_CLEANUP}" "$( "${this_dir}/build_command" cleanup )" \
  | /usr/local/libexec/kiwi-cron/randomize_schedule

echo "${SCHEDULE_RMFULL}"  "$( "${this_dir}/build_command" rmfull )" \
  | /usr/local/libexec/kiwi-cron/randomize_schedule

echo "${SCHEDULE_RMINCR}"  "$( "${this_dir}/build_command" rmincr )" \
  | /usr/local/libexec/kiwi-cron/randomize_schedule
